"""Private HTTP execution service behind Lambda's authenticated port-80 ingress.

AWS JWE access is the perimeter; never publish this port without that proxy.
Checkpoint/restore operations are launch-once and block all guest mutations.
"""
import ctypes
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
import os
from pathlib import Path
import shutil
import signal
import subprocess
import sys
import threading
import time
import urllib.request

try:
    from . import substrate_guest as guest, lambda_checkpoint as checkpoint
except ImportError:
    import substrate_guest as guest
    import lambda_checkpoint as checkpoint

ROOT = guest.ROOT
LOCK = threading.RLock()
JOBS = {}
ACTIVE = set()
BUSY = None
FROZEN = {}
MAX_ARCHIVE = 4 * 1024 ** 3
BOOTSTRAPPED = sys.argv[1:] == ['bootstrapped']


def thaw():
    for pid, start in list(FROZEN.items()):
        if guest.process_identity(pid)[0] == start:
            try:
                os.kill(int(pid), signal.SIGCONT)
            except ProcessLookupError:
                pass
    FROZEN.clear()


def freeze():
    """Freeze guest commands, including detached descendants, not AWS daemons."""
    try:
        for _ in range(20):
            found = False
            processes = {}
            for path in Path('/proc').iterdir():
                if not path.name.isdigit():
                    continue
                try:
                    fields = (path / 'stat').read_text().rsplit(')', 1)[1].split()
                    processes[int(path.name)] = (int(fields[1]), fields[19], fields[0])
                except (FileNotFoundError, PermissionError, ProcessLookupError):
                    continue
            owned = {os.getpid()}
            for _ in range(len(processes)):
                children = {pid for pid, (parent, _, _) in processes.items() if parent in owned}
                if children <= owned:
                    break
                owned |= children
            for pid in owned - {os.getpid()}:
                _, start, state = processes[pid]
                if state != 'Z' and str(pid) not in FROZEN:
                    FROZEN[str(pid)] = start
                    try:
                        os.kill(pid, signal.SIGSTOP)
                        found = True
                    except ProcessLookupError:
                        pass
            if not found and all(guest.process_identity(pid)[1] in {None, 'T', 't', 'Z'} for pid in FROZEN):
                return
            time.sleep(.02)
        raise RuntimeError('Guest commands did not quiesce')
    except BaseException:
        thaw()
        raise


def identity(value):
    if not isinstance(value, str) or len(value) != 32 or any(c not in '0123456789abcdef' for c in value):
        raise ValueError('Invalid operation ID')
    return value


def transfer(url, *, path, headers=None, upload=False):
    # URLs are narrow, short-lived capabilities generated by the server. They
    # are never written to disk or logs. Reject redirects to avoid leaking them.
    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args):
            return None
    if not url.startswith('https://'):
        raise ValueError('Checkpoint transfer requires HTTPS')
    opener = urllib.request.build_opener(NoRedirect())
    if upload:
        with path.open('rb') as stream:
            request = urllib.request.Request(url, data=stream, method='PUT', headers={
                'Content-Length': str(path.stat().st_size), **(headers or {})})
            with opener.open(request, timeout=60) as response:
                if response.status != 200:
                    raise RuntimeError('Checkpoint upload failed')
    else:
        with opener.open(url, timeout=60) as response, path.open('wb') as stream:
            size = 0
            while chunk := response.read(1024 * 1024):
                size += len(chunk)
                if size > MAX_ARCHIVE:
                    raise ValueError('Checkpoint download exceeds limit')
                stream.write(chunk)


def perform(path, body):
    global BUSY
    job_id = body['id']
    directory = ROOT / 'operations' / job_id
    directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    try:
        if path == '/initialize':
            restored = body.get('restore')
            if restored:
                archive = directory / 'restore.tar.gz'
                transfer(restored['url'], path=archive)
                if archive.stat().st_size != restored['size']:
                    raise ValueError('Checkpoint length mismatch')
                checkpoint.restore(archive, expected_sha256=restored['sha256'])
                archive.unlink()
            packages = body.get('apt_packages', [])
            if packages:
                if any(not isinstance(p, str) or not p or p.startswith('-') for p in packages):
                    raise ValueError('Invalid package name')
                subprocess.run(['apt-get', 'update'], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=300)
                subprocess.run(['apt-get', 'install', '-y', '--no-install-recommends', *packages], check=True,
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=600)
            guest.atomic(ROOT / 'initialized.json', {'id': job_id})
            result = {'ready': True}
        elif path == '/checkpoint':
            freeze()
            result = checkpoint.pack(directory / 'archive.tar.gz', max_bytes=min(body['max_bytes'], MAX_ARCHIVE))
        elif path == '/upload':
            archive = ROOT / 'operations' / identity(body['checkpoint']) / 'archive.tar.gz'
            transfer(body['url'], path=archive, upload=True,
                headers={'x-amz-checksum-sha256': body['checksum'], 'x-amz-server-side-encryption': 'AES256'})
            result = {'uploaded': True}
        else:
            raise ValueError('Invalid operation')
        with LOCK:
            # An expired checkpoint must never become successful afterwards.
            if JOBS[job_id]['state'] != 'failed':
                JOBS[job_id] = {'state': 'done', 'result': result}
                guest.atomic(directory / 'receipt.json', JOBS[job_id])
            if path == '/initialize':
                BUSY = None
    except BaseException as exc:
        with LOCK:
            JOBS[job_id] = {'state': 'failed', 'error': type(exc).__name__}
            guest.atomic(directory / 'receipt.json', JOBS[job_id])
            if path == '/upload' and BUSY:
                JOBS[BUSY] = {'state': 'failed', 'error': 'UploadFailed'}
            # A partially restored VM remains blocked until terminated.
    finally:
        with LOCK:
            ACTIVE.discard(job_id)
            if not ACTIVE and BUSY and JOBS.get(BUSY, {}).get('state') == 'failed' and path != '/initialize':
                thaw()
                shutil.rmtree(ROOT / 'operations' / BUSY, ignore_errors=True)
                BUSY = None


def expire_checkpoint(job_id, timeout):
    time.sleep(timeout)
    with LOCK:
        if BUSY == job_id:
            JOBS[job_id] = {'state': 'failed', 'error': 'CheckpointExpired'}
            # The worker owns the freeze until its file IO has settled. New
            # work stays blocked, including after the HTTP caller times out.
            if not ACTIVE:
                thaw()


def start_job(path, body):
    global BUSY
    job_id = identity(body['id'])
    receipt = ROOT / 'operations' / job_id / 'receipt.json'
    if job_id in JOBS:
        return JOBS[job_id]
    if receipt.exists():
        return json.loads(receipt.read_text())
    if path == '/initialize':
        ready = ROOT / 'initialized.json'
        if ready.exists():
            if json.loads(ready.read_text())['id'] != job_id:
                raise RuntimeError('VM belongs to another session')
            JOBS[job_id] = {'state': 'done', 'result': {'ready': True}}
            return JOBS[job_id]
    if path == '/upload':
        if BUSY != body['checkpoint'] or JOBS[BUSY]['state'] != 'done':
            raise RuntimeError('Checkpoint is not ready')
    elif BUSY:
        raise RuntimeError('Workspace operation already in progress')
    else:
        BUSY = job_id
    # Persist an uncertain receipt BEFORE work. A service restart must never
    # replay a half-completed restore or package installer.
    guest.atomic(receipt, {'state': 'failed', 'error': 'UncertainOperation'})
    JOBS[job_id] = {'state': 'running'}
    ACTIVE.add(job_id)
    threading.Thread(target=perform, args=(path, body), daemon=True).start()
    if path == '/checkpoint':
        threading.Thread(target=expire_checkpoint, args=(job_id, min(max(body['timeout'], 10), 600)), daemon=True).start()
    return {'state': 'running'}


def dispatch(path, body):
    global BUSY
    with LOCK:
        if path == '/health':
            return {'version': 1, 'bootstrapped': BOOTSTRAPPED}
        if not BOOTSTRAPPED:
            raise RuntimeError('VM must bootstrap before accepting work')
        if path == '/job':
            job_id = identity(body['id'])
            if job_id in JOBS:
                return JOBS[job_id]
            return json.loads((ROOT / 'operations' / job_id / 'receipt.json').read_text())
        if path == '/checkpoint/finish':
            if BUSY == identity(body['id']):
                # Only a settled operation can safely thaw and delete its files.
                if ACTIVE:
                    raise RuntimeError('Checkpoint still running')
                thaw()
                shutil.rmtree(ROOT / 'operations' / BUSY, ignore_errors=True)
                BUSY = None
            return {'ok': True}
        if path in {'/initialize', '/checkpoint', '/upload'}:
            return start_job(path, body)
        if BUSY or not (ROOT / 'initialized.json').exists():
            raise RuntimeError('Workspace is not ready')
        if path == '/computer':
            # Serialize Computer against checkpoint creation without journaling
            # typed text or repeating uncertain input.
            return guest.computer.request(body, start=guest.computer.starts_service(body))
        if path not in {'/start', '/read', '/file/write', '/file/read', '/file/stat'}:
            raise ValueError('Unknown operation')
        return guest.dispatch(path, body)


class Handler(BaseHTTPRequestHandler):
    protocol_version = 'HTTP/1.0'

    def log_message(self, *args):
        pass

    def reply(self, code, value):
        data = json.dumps(value).encode()
        self.send_response(code)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self):
        ready = self.path in {'/health', '/aws/lambda-microvms/runtime/v1/ready'}
        self.reply(200 if ready else 404, {'version': 1, 'bootstrapped': BOOTSTRAPPED})

    def do_POST(self):
        if self.path == '/bootstrap':
            # Every image restore gets a fresh interpreter and fresh TLS/RNG
            # state before accepting commands. No TLS client is snapshotted.
            self.reply(200, {'ok': True})
            self.wfile.flush()
            if not BOOTSTRAPPED:
                os.execv(sys.executable, [sys.executable, __file__, 'bootstrapped'])
            return
        try:
            length = int(self.headers.get('Content-Length', 0))
            if not 0 < length <= 2 * 1024 * 1024:
                return self.reply(413, {'error': 'Request too large'})
            self.connection.settimeout(30)
            self.reply(200, dispatch(self.path, json.loads(self.rfile.read(length))))
        except FileNotFoundError:
            self.reply(404, {'error': 'File or operation not found'})
        except Exception:
            self.reply(409, {'error': 'Workspace operation failed'})


if __name__ == '__main__':
    if sys.argv[1:] == ['baseline']:
        checkpoint.baseline()
    else:
        # Reparent double-forked/env-cleared daemons to this service, keeping
        # the complete command tree quiesceable without stopping AWS daemons.
        if ctypes.CDLL(None, use_errno=True).prctl(36, 1, 0, 0, 0):  # PR_SET_CHILD_SUBREAPER
            raise OSError(ctypes.get_errno(), 'Could not own detached guest processes')
        ROOT.mkdir(parents=True, exist_ok=True, mode=0o700)
        ThreadingHTTPServer(('0.0.0.0', 80), Handler).serve_forever()
