"""Database operations whose transaction or schema semantics differ by backend.

Queries use portable SQL and qmark bindings. PostgreSQL never retries a write or
falls back to a local database. The writer lock preserves today's single-writer
transactions until job ownership is made safe for multiple application instances.
"""
from contextlib import contextmanager
from decimal import Decimal
from functools import lru_cache
import json
import re
import sqlite3


class DatabaseError(RuntimeError):
    """Safe to report without SQL, parameters, or connection credentials."""


class IntegrityError(DatabaseError):
    pass


INTEGRITY_ERRORS = (sqlite3.IntegrityError, IntegrityError)

# Quoted strings/identifiers and comments must not be rewritten as parameters or
# schema keywords. Application SQL does not use dollar-quoted query literals.
SQL_PARTS = re.compile(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|--[^\n]*(?:\n|$)|/\*[\s\S]*?\*/)")


@lru_cache(maxsize=2048)
def bindings(statement: str) -> str:
    parts = SQL_PARTS.split(statement)
    return ''.join(part.replace('%', '%%').replace('?', '%s') if i % 2 == 0
                   else part.replace('%', '%%') for i, part in enumerate(parts))


def identifier(name: str) -> str:
    if not re.fullmatch(r'[a-z][a-z0-9_]{0,62}', name):
        raise ValueError('Invalid database identifier.')
    return '"' + name + '"'


@lru_cache(maxsize=256)
def schema_sql(statement: str) -> str:
    """The four schema types used by Moyai, with explicit Postgres identities.

    This only handles CREATE TABLE/INDEX and ALTER TABLE from application source;
    runtime queries, triggers and views are not translated.
    """
    parts = SQL_PARTS.split(statement)
    for i in range(0, len(parts), 2):
        part = re.sub(r'\bINTEGER\s+PRIMARY\s+KEY(?:\s+AUTOINCREMENT)?\b',
                      'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', parts[i], flags=re.I)
        for source, target in [('INTEGER', 'BIGINT'), ('REAL', 'DOUBLE PRECISION'), ('BLOB', 'BYTEA')]:
            part = re.sub(r'\b' + source + r'\b', target, part, flags=re.I)
        parts[i] = part
    return ''.join(parts)


def json_value(document, key):
    value = json.loads(document).get(key) if document is not None else None
    return value


class SQLiteConnection(sqlite3.Connection):
    def begin_write(self):
        self.execute('BEGIN IMMEDIATE')

    def begin_read(self):
        self.execute('BEGIN')

    def column_names(self, table):
        return {row['name'] for row in self.execute(f'PRAGMA table_info({identifier(table)})')}

    def table_names(self):
        return {row['name'] for row in self.execute("SELECT name FROM sqlite_master WHERE type='table'")}

    def create_view(self, name, query):
        self.execute(f'CREATE VIEW IF NOT EXISTS {identifier(name)} AS {query}')

    def event_ranges_predicate(self):
        return """EXISTS (SELECT 1 FROM json_each(?) AS span
            WHERE e.id>=json_extract(span.value,'$[0]')
            AND (json_extract(span.value,'$[1]') IS NULL OR e.id<json_extract(span.value,'$[1]')))"""


def sqlite_connection(path):
    conn = sqlite3.connect(path, timeout=10, factory=SQLiteConnection)
    conn.row_factory = sqlite3.Row
    conn.create_function('unicode_lower', 1, str.lower, deterministic=True)
    conn.create_function('strpos', 2, lambda text, term: text.find(term) + 1, deterministic=True)
    conn.create_function('greatest', 2, max, deterministic=True)
    conn.create_function('json_text', 2, lambda doc, key: (
        str(v) if isinstance(v := json_value(doc, key), (str, int, float)) else None), deterministic=True)
    conn.create_function('json_number', 2, lambda doc, key: (
        v if isinstance(v := json_value(doc, key), (int, float)) else None), deterministic=True)
    conn.execute('PRAGMA foreign_keys=ON')
    return conn


class Row:
    """Like sqlite3.Row: named/positional access and dict(row), without coercion."""
    def __init__(self, names, values):
        self.names = names
        self.values = tuple(int(v) if isinstance(v, Decimal) and v == int(v) else v for v in values)

    def keys(self):
        return self.names

    def __getitem__(self, key):
        return self.values[self.names.index(key)] if isinstance(key, str) else self.values[key]

    def __iter__(self):
        return iter(self.values)

    def __len__(self):
        return len(self.values)


def row_factory(cursor):
    names = tuple(column.name for column in cursor.description) if cursor.description else ()
    return lambda values: Row(names, values)


class PostgresConnection:
    def __init__(self, raw, schema, owner_pid):
        self.raw, self.schema, self.owner_pid = raw, schema, owner_pid
        self.changed = False
        self.write_locked = False
        self.owner_checked = False

    def begin_write(self):
        if not self.write_locked:
            self.raw.execute('SELECT pg_advisory_xact_lock(726941, %s::regnamespace::oid::int)', (self.schema,))
            self.check_owner()
            self.write_locked = True

    def check_owner(self):
        if self.owner_pid is None:
            self.owner_checked = True
            return
        owned = self.raw.execute('''SELECT 1 FROM pg_locks WHERE locktype='advisory'
            AND pid=%s AND classid=726940 AND objid=%s::regnamespace::oid
            AND objsubid=2 AND granted''', (self.owner_pid, self.schema)).fetchone()
        if not owned:
            raise DatabaseError('Postgres ownership was lost. Restart the single application instance.')
        self.owner_checked = True

    def begin_read(self):
        # Read projections and their SSE cursor must come from the same snapshot.
        # Must precede any SELECT in this transaction, including ownership checks.
        self.raw.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY')

    def execute(self, statement, params=()):
        # Ignore literals/comments when classifying CTEs or leading comments.
        unquoted = ' '.join(SQL_PARTS.split(statement)[::2])
        if re.search(r'\b(INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|TRUNCATE)\b', unquoted, re.I):
            self.begin_write()
            self.changed = True
        elif not self.owner_checked:
            self.check_owner()
        if re.match(r'\s*(CREATE\s+(?:TABLE|(?:UNIQUE\s+)?INDEX)|ALTER\s+TABLE)\b', unquoted, re.I):
            statement = schema_sql(statement)
        # Moyai's persisted flags are integers on both backends.
        values = tuple(int(value) if isinstance(value, bool) else value for value in params)
        return self.raw.execute(bindings(statement), values)

    def executemany(self, statement, parameters):
        # Keep one transaction/lock across the whole batch.
        for values in parameters:
            self.execute(statement, values)

    def executescript(self, script):
        # Split only outside literals/comments; these are plain schema scripts.
        statement = ''
        for i, part in enumerate(SQL_PARTS.split(script)):
            pieces = part.split(';') if i % 2 == 0 else [part]
            for offset, piece in enumerate(pieces):
                if offset:
                    if statement.strip():
                        self.execute(statement)
                    statement = ''
                statement += piece
        if statement.strip():
            self.execute(statement)

    def column_names(self, table):
        if not self.owner_checked:
            self.check_owner()
        return {row[0] for row in self.raw.execute('''SELECT column_name FROM information_schema.columns
            WHERE table_schema=%s AND table_name=%s''', (self.schema, table))}

    def table_names(self):
        if not self.owner_checked:
            self.check_owner()
        return {row[0] for row in self.raw.execute('SELECT tablename FROM pg_tables WHERE schemaname=%s', (self.schema,))}

    def create_view(self, name, query):
        self.begin_write()
        if not self.raw.execute('SELECT 1 FROM pg_views WHERE schemaname=%s AND viewname=%s', (self.schema, name)).fetchone():
            self.raw.execute(f'CREATE VIEW {identifier(name)} AS {query}')

    def event_ranges_predicate(self):
        return """EXISTS (SELECT 1 FROM jsonb_array_elements(CAST(? AS jsonb)) AS span(value)
            WHERE e.id>=(span.value->>0)::bigint
            AND ((span.value->>1) IS NULL OR e.id<(span.value->>1)::bigint))"""


class PostgresDatabase:
    def __init__(self, url, schema, *, initialize=False, application_instance=False):
        import psycopg
        from psycopg_pool import ConnectionPool

        identifier(schema)
        self.schema = schema
        self.pool = None
        try:
            # A session lock prevents a second process from running global
            # startup recovery. Keep this connection for the Store's lifetime.
            self.owner = psycopg.connect(url, autocommit=True, connect_timeout=10)
            self.owner.execute("SET lock_timeout = '10s'")
            self.owner.execute("SET statement_timeout = '30s'")
            self.owner_pid = self.owner.info.backend_pid if application_instance else None
            if not self.owner.execute('SELECT 1 FROM pg_namespace WHERE nspname=%s', (schema,)).fetchone():
                raise DatabaseError('Postgres schema does not exist. Import a verified copy or create an empty schema explicitly.')
            tables = {r[0] for r in self.owner.execute('SELECT tablename FROM pg_tables WHERE schemaname=%s', (schema,))}
            if (not tables and not initialize) or (tables and 'runs' not in tables):
                raise DatabaseError('Postgres schema is not an initialized Moyai database. Import a verified copy; empty initialization requires MOYAI_DATABASE_INITIALIZE=true.')
            if application_instance:
                locked = self.owner.execute('SELECT pg_try_advisory_lock(726940, %s::regnamespace::oid::int)', (schema,)).fetchone()[0]
                if not locked:
                    raise DatabaseError('Another Moyai instance owns this Postgres schema. Keep a single application instance.')
            with self.owner.transaction():
                self.owner.execute('SELECT pg_advisory_xact_lock(726941, %s::regnamespace::oid::int)', (schema,))
                self.owner.execute(f'SET LOCAL search_path TO {identifier(schema)}, pg_catalog')
                self.owner.execute('''CREATE OR REPLACE FUNCTION unicode_lower(text) RETURNS text
                    LANGUAGE sql IMMUTABLE STRICT AS 'SELECT lower($1)' ''')
                self.owner.execute('''CREATE OR REPLACE FUNCTION json_text(text,text) RETURNS text
                    LANGUAGE sql IMMUTABLE STRICT AS 'SELECT $1::jsonb ->> $2' ''')
                self.owner.execute('''CREATE OR REPLACE FUNCTION json_number(text,text) RETURNS numeric
                    LANGUAGE sql IMMUTABLE STRICT AS $fn$
                    SELECT CASE jsonb_typeof($1::jsonb -> $2)
                        WHEN 'number' THEN ($1::jsonb ->> $2)::numeric
                        WHEN 'boolean' THEN CASE WHEN ($1::jsonb ->> $2)::boolean THEN 1 ELSE 0 END
                        ELSE NULL END $fn$''')

            def configure(conn):
                conn.execute(f'SET search_path TO {identifier(schema)}, pg_catalog')
                conn.execute("SET lock_timeout = '10s'")
                conn.execute("SET statement_timeout = '30s'")
                conn.commit()

            self.pool = ConnectionPool(url, min_size=1, max_size=8, timeout=10,
                                       kwargs={'connect_timeout': 10, 'cursor_factory': psycopg.ClientCursor,
                                               'row_factory': row_factory},
                                       configure=configure, open=False)
            self.pool.open(wait=True, timeout=10)
        except Exception as exc:
            self.close()
            if isinstance(exc, DatabaseError):
                raise
            raise DatabaseError('Postgres initialization failed. Check database availability and configuration.') from None

    @contextmanager
    def connect(self):
        import psycopg

        try:
            # Failure of the ownership session fences all further application
            # operations; never reconnect it behind a running recovery loop.
            if self.owner_pid is not None and (self.owner.closed or self.owner.broken):
                raise DatabaseError('Postgres ownership connection was lost. Restart the single application instance.')
            with self.pool.connection() as raw:
                yield PostgresConnection(raw, self.schema, self.owner_pid)
        except psycopg.IntegrityError:
            raise IntegrityError('Database constraint rejected the change.') from None
        except psycopg.Error:
            raise DatabaseError('Postgres operation failed; the transaction was not acknowledged.') from None

    def close(self):
        if self.pool is not None:
            self.pool.close()
        if getattr(self, 'owner', None) is not None:
            self.owner.close()


Connection = SQLiteConnection | PostgresConnection
DatabaseRow = sqlite3.Row | Row
