"""Database operations whose transaction or schema semantics differ by backend.

Queries use portable SQL and qmark bindings. PostgreSQL never retries a write or
falls back to a local database. Cross-session decisions retain the exclusive
writer lock; explicitly scoped session writes share it and lock only their run.
"""
from contextlib import contextmanager
from decimal import Decimal
from functools import lru_cache
import hashlib
import json
import re
import sqlite3


class DatabaseError(RuntimeError):
    """Safe to report without SQL, parameters, or connection credentials."""


class IntegrityError(DatabaseError):
    pass


def runtime_fingerprint(settings):
    names = ('session_secret', 'encryption_key', 'object_storage_bucket', 'object_storage_endpoint',
             'object_storage_prefix', 'public_url', 'temporal_address', 'temporal_namespace', 'temporal_task_queue',
             'max_concurrent_runs', 'max_pending_runs', 'max_concurrent_model_requests', 'moyai_build_sha',
             'moyai_separate_broker', 'sandbox_prepared_pool_size', 'sandbox_prepared_idle_seconds')
    return hashlib.sha256(json.dumps({name: getattr(settings, name) for name in names}, sort_keys=True).encode()).hexdigest()


INTEGRITY_ERRORS = (sqlite3.IntegrityError, IntegrityError)

# Quoted strings/identifiers and comments must not be rewritten as parameters or
# schema keywords. Application SQL does not use dollar-quoted query literals.
SQL_PARTS = re.compile(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|--[^\n]*(?:\n|$)|/\*[\s\S]*?\*/)")


@lru_cache(maxsize=2048)
def bindings(statement: str) -> str:
    parts = SQL_PARTS.split(statement)
    return ''.join(part.replace('%', '%%').replace('?', '%s') if i % 2 == 0
                   else part.replace('%', '%%') for i, part in enumerate(parts))


def identifier(name: str) -> str:
    if not re.fullmatch(r'[a-z][a-z0-9_]{0,62}', name):
        raise ValueError('Invalid database identifier.')
    return '"' + name + '"'


@lru_cache(maxsize=256)
def schema_sql(statement: str) -> str:
    """The four schema types used by Moyai, with explicit Postgres identities.

    This only handles CREATE TABLE/INDEX and ALTER TABLE from application source;
    runtime queries, triggers and views are not translated.
    """
    parts = SQL_PARTS.split(statement)
    for i in range(0, len(parts), 2):
        part = re.sub(r'\bINTEGER\s+PRIMARY\s+KEY(?:\s+AUTOINCREMENT)?\b',
                      'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', parts[i], flags=re.I)
        for source, target in [('INTEGER', 'BIGINT'), ('REAL', 'DOUBLE PRECISION'), ('BLOB', 'BYTEA')]:
            part = re.sub(r'\b' + source + r'\b', target, part, flags=re.I)
        parts[i] = part
    return ''.join(parts)


def json_value(document, key):
    value = json.loads(document) if document is not None else None
    return value.get(key) if isinstance(value, dict) else None


class SQLiteConnection(sqlite3.Connection):
    def begin_write(self):
        self.execute('BEGIN IMMEDIATE')

    def begin_read(self):
        self.execute('BEGIN')

    def column_names(self, table):
        return {row['name'] for row in self.execute(f'PRAGMA table_info({identifier(table)})')}

    def table_names(self):
        return {row['name'] for row in self.execute("SELECT name FROM sqlite_master WHERE type='table'")}

    def create_view(self, name, query):
        self.execute(f'CREATE VIEW IF NOT EXISTS {identifier(name)} AS {query}')

    def event_ranges_predicate(self):
        return """EXISTS (SELECT 1 FROM json_each(?) AS span
            WHERE e.id>=json_extract(span.value,'$[0]')
            AND (json_extract(span.value,'$[1]') IS NULL OR e.id<json_extract(span.value,'$[1]')))"""


def sqlite_connection(path):
    conn = sqlite3.connect(path, timeout=10, factory=SQLiteConnection)
    conn.row_factory = sqlite3.Row
    conn.create_function('unicode_lower', 1, str.lower, deterministic=True)
    conn.create_function('strpos', 2, lambda text, term: text.find(term) + 1, deterministic=True)
    conn.create_function('greatest', 2, max, deterministic=True)
    conn.create_function('json_text', 2, lambda doc, key: (
        v if isinstance(v := json_value(doc, key), str) else None), deterministic=True)
    conn.create_function('json_number', 2, lambda doc, key: (
        v if isinstance(v := json_value(doc, key), (int, float)) else None), deterministic=True)
    conn.execute('PRAGMA foreign_keys=ON')
    return conn


class Row:
    """Named/positional access and dict(row), with Python numeric aggregates."""
    def __init__(self, names, values):
        self.names = names
        self.values = tuple((int(v) if v == int(v) else float(v)) if isinstance(v, Decimal) else v for v in values)

    def keys(self):
        return self.names

    def __getitem__(self, key):
        return self.values[self.names.index(key)] if isinstance(key, str) else self.values[key]

    def __iter__(self):
        return iter(self.values)

    def __len__(self):
        return len(self.values)


def row_factory(cursor):
    names = tuple(column.name for column in cursor.description) if cursor.description else ()
    return lambda values: Row(names, values)


class PostgresConnection:
    def __init__(self, raw, schema, owner_pid, *, write_scope=None, policy='', schema_updates=True):
        self.raw, self.schema, self.owner_pid = raw, schema, owner_pid
        self.write_scope, self.policy = write_scope, policy
        self.changed = False
        self.write_locked = False
        self.owner_checked = False
        self.schema_updates = schema_updates

    def begin_write(self):
        if not self.write_locked:
            if self.write_scope is None:
                self.raw.execute('SELECT pg_advisory_xact_lock(726941, %s::regnamespace::oid::int)', (self.schema,))
            else:
                # Independent session writes can proceed together. Legacy or
                # cross-session transactions retain an exclusive schema lock.
                self.raw.execute('SELECT pg_advisory_xact_lock_shared(726941, %s::regnamespace::oid::int)', (self.schema,))
                key = int.from_bytes(hashlib.sha256((self.schema + ':' + self.write_scope).encode()).digest()[:8], 'big', signed=True)
                self.raw.execute('SELECT pg_advisory_xact_lock(%s::bigint)', (key,))
            self.check_owner()
            from .runtime_coordination import held_leases
            for lease in held_leases.get():
                if lease.schema != self.schema:
                    raise DatabaseError('Execution ownership belongs to a different database.')
                if not self.raw.execute('''SELECT 1 FROM runtime_leases
                    WHERE name=%s AND token=%s AND expires_at>clock_timestamp() FOR SHARE''',
                    (lease.name, lease.token)).fetchone():
                    raise DatabaseError('Execution ownership expired. The transaction was not acknowledged.')
            self.write_locked = True

    def check_owner(self):
        if self.owner_pid is None:
            self.owner_checked = True
            return
        owned = self.raw.execute('''SELECT 1 FROM pg_locks WHERE locktype='advisory'
            AND pid=%s AND classid=726940 AND objid=%s::regnamespace::oid
            AND objsubid=2 AND granted''', (self.owner_pid, self.schema)).fetchone()
        if not owned:
            raise DatabaseError('Postgres ownership was lost. Restart this application process.')
        if self.policy and not self.raw.execute('SELECT 1 FROM runtime_policy WHERE id=1 AND fingerprint=%s', (self.policy,)).fetchone():
            raise DatabaseError('Runtime configuration changed. Restart workers with the coordinator configuration.')
        self.owner_checked = True

    def begin_read(self):
        # Read projections and their SSE cursor must come from the same snapshot.
        # Must precede any SELECT in this transaction, including ownership checks.
        self.raw.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY')

    def execute(self, statement, params=()):
        # Ignore literals/comments when classifying CTEs or leading comments.
        unquoted = ' '.join(SQL_PARTS.split(statement)[::2])
        if not self.schema_updates and re.search(r'\b(CREATE|ALTER|DROP|TRUNCATE|REINDEX)\b', unquoted, re.I):
            raise DatabaseError('Schema changes require the offline migration command.')
        if re.search(r'\b(INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|TRUNCATE)\b', unquoted, re.I):
            self.begin_write()
            self.changed = True
        elif not self.owner_checked:
            self.check_owner()
        if re.match(r'\s*(CREATE\s+(?:TABLE|(?:UNIQUE\s+)?INDEX)|ALTER\s+TABLE)\b', unquoted, re.I):
            statement = schema_sql(statement)
        # Moyai's persisted flags are integers on both backends.
        values = tuple(int(value) if isinstance(value, bool) else value for value in params)
        return self.raw.execute(bindings(statement), values)

    def executemany(self, statement, parameters):
        # Keep one transaction/lock across the whole batch.
        for values in parameters:
            self.execute(statement, values)

    def executescript(self, script):
        # Split only outside literals/comments; these are plain schema scripts.
        statement = ''
        for i, part in enumerate(SQL_PARTS.split(script)):
            pieces = part.split(';') if i % 2 == 0 else [part]
            for offset, piece in enumerate(pieces):
                if offset:
                    if statement.strip():
                        self.execute(statement)
                    statement = ''
                statement += piece
        if statement.strip():
            self.execute(statement)

    def column_names(self, table):
        if not self.owner_checked:
            self.check_owner()
        return {row[0] for row in self.raw.execute('''SELECT column_name FROM information_schema.columns
            WHERE table_schema=%s AND table_name=%s''', (self.schema, table))}

    def table_names(self):
        if not self.owner_checked:
            self.check_owner()
        return {row[0] for row in self.raw.execute('SELECT tablename FROM pg_tables WHERE schemaname=%s', (self.schema,))}

    def create_view(self, name, query):
        if not self.schema_updates:
            raise DatabaseError('Schema changes require the offline migration command.')
        self.begin_write()
        if not self.raw.execute('SELECT 1 FROM pg_views WHERE schemaname=%s AND viewname=%s', (self.schema, name)).fetchone():
            self.raw.execute(f'CREATE VIEW {identifier(name)} AS {query}')

    def event_ranges_predicate(self):
        return """EXISTS (SELECT 1 FROM jsonb_array_elements(CAST(? AS jsonb)) AS span(value)
            WHERE e.id>=(span.value->>0)::bigint
            AND ((span.value->>1) IS NULL OR e.id<(span.value->>1)::bigint))"""


class PostgresDatabase:
    def __init__(self, url, schema, *, initialize=False, application_instance=False, pool_size=8, runtime_role='standalone', runtime_settings=None, schema_mode='auto'):
        import psycopg
        from psycopg_pool import ConnectionPool

        identifier(schema)
        self.schema = schema
        self.runtime_role, self.policy = runtime_role, ''
        self.broker_owner = False
        self.startup_exclusive = False
        self.pool = None
        if schema_mode not in {'auto', 'verify', 'migrate'}:
            raise ValueError('Unknown schema mode.')
        if schema_mode == 'migrate' and (not application_instance or runtime_role != 'standalone'):
            raise ValueError('Schema migration requires exclusive application ownership.')
        self.schema_updates = schema_mode != 'verify'
        if application_instance and runtime_role != 'standalone' and runtime_settings is None:
            raise DatabaseError('Distributed application startup requires its runtime configuration before schema setup.')
        try:
            # A session lock prevents a second process from running global
            # startup recovery. Keep this connection for the Store's lifetime.
            self.owner = psycopg.connect(url, autocommit=True, connect_timeout=10)
            self.owner.execute("SET lock_timeout = '10s'")
            self.owner.execute("SET statement_timeout = '30s'")
            self.owner_pid = self.owner.info.backend_pid if application_instance else None
            if not self.owner.execute('SELECT 1 FROM pg_namespace WHERE nspname=%s', (schema,)).fetchone():
                raise DatabaseError('Postgres schema does not exist. Import a verified copy or create an empty schema explicitly.')
            tables = {r[0] for r in self.owner.execute('SELECT tablename FROM pg_tables WHERE schemaname=%s', (schema,))}
            if (not tables and not initialize) or (tables and 'runs' not in tables and not (schema_mode == 'migrate' and 'schema_state' in tables)):
                raise DatabaseError('Postgres schema is not an initialized Moyai database. Import a verified copy; empty initialization requires MOYAI_DATABASE_INITIALIZE=true.')
            if application_instance:
                function = 'pg_try_advisory_lock' if runtime_role == 'standalone' else 'pg_try_advisory_lock_shared'
                locked = self.owner.execute(f'SELECT {function}(726940, %s::regnamespace::oid::int)', (schema,)).fetchone()[0]
                if not locked:
                    raise DatabaseError('Another Moyai instance owns this Postgres schema. Keep a single application instance.')
                if runtime_role == 'coordinator' and not self.owner.execute(
                        'SELECT pg_try_advisory_lock(726943, %s::regnamespace::oid::int)', (schema,)).fetchone()[0]:
                    raise DatabaseError('Another coordinator owns this Postgres schema.')
                if runtime_settings is not None and runtime_role != 'standalone':
                    # Reject incompatible builds/keys and duplicate brokers before
                    # even CREATE IF NOT EXISTS or legacy data backfills can run.
                    self.admit_runtime(runtime_settings)
            from .schema_migrations import prepare_schema
            prepare_schema(self.owner, schema, schema_mode)
            if self.schema_updates:
                self._initialize_schema()

            def configure(conn):
                conn.execute(f'SET search_path TO {identifier(schema)}, pg_catalog')
                conn.execute("SET TIME ZONE 'UTC'")
                conn.execute("SET lock_timeout = '10s'")
                conn.execute("SET statement_timeout = '30s'")
                conn.commit()

            self.pool = ConnectionPool(url, min_size=1, max_size=pool_size, timeout=10,
                                       kwargs={'connect_timeout': 10, 'cursor_factory': psycopg.ClientCursor,
                                               'row_factory': row_factory},
                                       configure=configure, open=False)
            self.pool.open(wait=True, timeout=10)
        except Exception as exc:
            self.close()
            if isinstance(exc, DatabaseError):
                raise
            raise DatabaseError('Postgres initialization failed. Check database availability and configuration.') from None

    def _initialize_schema(self):
        schema = self.schema
        with self.owner.transaction():
            self.owner.execute('SELECT pg_advisory_xact_lock(726941, %s::regnamespace::oid::int)', (schema,))
            self.owner.execute(f'SET LOCAL search_path TO {identifier(schema)}, pg_catalog')
            self.owner.execute('''CREATE TABLE IF NOT EXISTS runtime_leases (
                name TEXT PRIMARY KEY, token TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL)''')
            self.owner.execute('''CREATE TABLE IF NOT EXISTS runtime_policy (
                id INTEGER PRIMARY KEY CHECK(id=1), fingerprint TEXT NOT NULL)''')
            self.owner.execute('''CREATE OR REPLACE FUNCTION unicode_lower(text) RETURNS text
                LANGUAGE sql IMMUTABLE STRICT AS 'SELECT lower($1)' ''')
            self.owner.execute('''CREATE OR REPLACE FUNCTION json_text(text,text) RETURNS text
                LANGUAGE sql IMMUTABLE STRICT AS $fn$
                SELECT CASE WHEN jsonb_typeof($1::jsonb -> $2)='string' THEN $1::jsonb ->> $2 END $fn$''')
            self.owner.execute('''CREATE OR REPLACE FUNCTION json_number(text,text) RETURNS numeric
                LANGUAGE sql IMMUTABLE STRICT AS $fn$
                SELECT CASE jsonb_typeof($1::jsonb -> $2)
                    WHEN 'number' THEN ($1::jsonb ->> $2)::numeric
                    WHEN 'boolean' THEN CASE WHEN ($1::jsonb ->> $2)::boolean THEN 1 ELSE 0 END
                    ELSE NULL END $fn$''')

    @contextmanager
    def connect(self, *, write_scope=None):
        import psycopg

        try:
            # Failure of the ownership session fences all further application
            # operations; never reconnect it behind a running recovery loop.
            if self.owner_pid is not None and (self.owner.closed or self.owner.broken):
                raise DatabaseError('Postgres ownership connection was lost. Restart this application process.')
            with self.pool.connection() as raw:
                yield PostgresConnection(raw, self.schema, self.owner_pid, write_scope=write_scope, policy=self.policy,
                                         schema_updates=self.schema_updates)
        except psycopg.IntegrityError:
            raise IntegrityError('Database constraint rejected the change.') from None
        except psycopg.Error:
            raise DatabaseError('Postgres operation failed; the transaction was not acknowledged.') from None

    def stored_policy(self):
        if not self.owner.execute('SELECT to_regclass(%s)',
                                  (f'{identifier(self.schema)}.runtime_policy',)).fetchone()[0]:
            return None
        row = self.owner.execute(f'SELECT fingerprint FROM {identifier(self.schema)}.runtime_policy WHERE id=1').fetchone()
        return row[0] if row else None

    def admit_runtime(self, settings):
        if settings.moyai_runtime_role != self.runtime_role:
            raise DatabaseError('Runtime role does not match the database owner.')
        owns_broker = self.runtime_role == 'broker' or (
            self.runtime_role == 'coordinator' and not settings.moyai_separate_broker)
        if owns_broker and self.owner_pid is not None and not self.broker_owner:
            if not self.owner.execute('SELECT pg_try_advisory_lock(726944, %s::regnamespace::oid::int)',
                                      (self.schema,)).fetchone()[0]:
                raise DatabaseError('Another inference broker owns this Postgres schema.')
            self.broker_owner = True
        policy = runtime_fingerprint(settings)
        if self.stored_policy() != policy:
            if self.runtime_role != 'coordinator':
                raise DatabaseError('Start the coordinator first, with the same shared runtime configuration.')
            if not self.startup_exclusive:
                # Upgrade our shared runtime lock without waiting. This both
                # proves old workers/brokers have exited and prevents new ones
                # from joining while the replacement constructs its schema.
                if not self.owner.execute('SELECT pg_try_advisory_lock(726940, %s::regnamespace::oid::int)',
                                          (self.schema,)).fetchone()[0]:
                    raise DatabaseError('Drain and stop other runtime owners before changing the shared runtime configuration.')
                self.startup_exclusive = True
        elif not self.policy:
            self.policy = policy
        return policy

    def configure_runtime(self, settings):
        if self.runtime_role == 'standalone':
            return
        policy = self.admit_runtime(settings)
        try:
            with self.connect() as conn:
                if self.runtime_role == 'coordinator':
                    conn.execute('INSERT INTO runtime_policy VALUES(1,?) ON CONFLICT(id) DO UPDATE SET fingerprint=excluded.fingerprint', (policy,))
                elif not conn.execute('SELECT 1 FROM runtime_policy WHERE id=1 AND fingerprint=?', (policy,)).fetchone():
                    raise DatabaseError('Start the coordinator first, with the same shared runtime configuration.')
            self.policy = policy
        finally:
            if self.startup_exclusive:
                self.owner.execute('SELECT pg_advisory_unlock(726940, %s::regnamespace::oid::int)', (self.schema,))
                self.startup_exclusive = False

    def acquire_lease(self, name, token, ttl):
        with self.connect() as conn:
            conn.check_owner()
            # Serialize contenders without waiting, including when the row is
            # not visible yet because another acquisition has not committed.
            key = int.from_bytes(hashlib.sha256((self.schema + ':lease:' + name).encode()).digest()[:8], 'big', signed=True)
            if not conn.raw.execute('SELECT pg_try_advisory_xact_lock(%s::bigint)', (key,)).fetchone()[0]:
                return False
            # Owner writes fence themselves with FOR SHARE. Skip their row
            # rather than holding global admission behind the write. A second
            # read distinguishes a locked row from an absent one; the advisory
            # lock excludes concurrent creation during this check and insert.
            row = conn.raw.execute('SELECT name FROM runtime_leases WHERE name=%s FOR UPDATE SKIP LOCKED', (name,)).fetchone()
            if row is None and conn.raw.execute('SELECT 1 FROM runtime_leases WHERE name=%s', (name,)).fetchone():
                return False
            return bool(conn.raw.execute('''INSERT INTO runtime_leases VALUES(%s,%s,clock_timestamp()+%s*interval '1 second')
                ON CONFLICT(name) DO UPDATE SET token=excluded.token,expires_at=clock_timestamp()+%s*interval '1 second'
                WHERE runtime_leases.expires_at<=clock_timestamp() RETURNING token''', (name, token, ttl, ttl)).fetchone())

    def renew_lease(self, name, token, ttl):
        with self.connect() as conn:
            conn.check_owner()
            return bool(conn.raw.execute('''UPDATE runtime_leases SET expires_at=clock_timestamp()+%s*interval '1 second'
                WHERE name=%s AND token=%s AND expires_at>clock_timestamp() RETURNING token''', (ttl, name, token)).fetchone())

    def release_lease(self, name, token):
        with self.connect() as conn:
            conn.check_owner()
            conn.raw.execute('DELETE FROM runtime_leases WHERE name=%s AND token=%s', (name, token))

    def close(self):
        if self.pool is not None:
            self.pool.close()
        if getattr(self, 'owner', None) is not None:
            self.owner.close()


Connection = SQLiteConnection | PostgresConnection
DatabaseRow = sqlite3.Row | Row
